const String bartinMerkezCity = 'Bartın Merkez';

const List<String> bartinMerkezMahalleleri = [
  'Ağdacı',
  'Aladağ',
  'Çaydüzü',
  'Cumhuriyet',
  'Demirciler',
  'Esentepe',
  'Gecen',
  'Gölbucağı',
  'Hürriyet',
  'Karaçay',
  'Karaköy',
  'Kemerköprü',
  'Kırtepe',
  'Köyortası',
  'Okulak',
  'Orduyeri',
  'Orta',
  'Şiremirçavuş',
  'Tuna',
  'Yıldız',
  'Şabankadı',
  'Yenişar',
  'Gürgenpınarı',
  'Kavlaklık',
  'Demirci Ahmetler',
  'Uzunöz',
  'Değirmenci',
  'Gerişli',
  'Tüloğlu',
];
